spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/budgetapp
    username: budgetapp
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      enabled: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    cleanDisabled: false
    enabled: false
